from django.shortcuts import render
import random

# Create your views here.

fortunes = [
    "The early bird gets the worm, but the second mouse gets the cheese.",
    "Happiness is a warm puppy.",
    "You will receive a pleasant surprise soon.",
    "A journey of a thousand miles begins with a single step.",
    "The best is yet to come.",
    "Don't count your chickens before they hatch.",
    "A smile is your passport into the hearts of others.",
    "Believe you can and you're halfway there.",
    "Good things come to those who wait.",
    "The only way to do great work is to love what you do.",
    "Your future is bright.",
    "Today is a good day to try something new.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "Let your dreams be your guide.",
    "You are capable of more than you know.",
    "Every day is a second chance.",
    "The smallest act of kindness is worth more than the grandest intention.",
    "Learn from yesterday, live for today, hope for tomorrow.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "You will be successful in your endeavors.",
    "A kind word is like a spring day.",
    "The harder you work, the luckier you get.",
    "Your creativity will open many doors.",
    "Embrace the glorious mess that you are.",
    "The best view comes after the hardest climb.",
    "You will find happiness in unexpected places.",
    "Let your intuition be your guide.",
    "The time is always right to do what is right.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "You are surrounded by love.",
    "A little progress each day adds up to big results.",
    "The journey is the reward.",
    "Your efforts will be recognized.",
    "Open your mind to new possibilities.",
    "The greatest discovery is self-discovery.",
    "You will make a positive difference in the world.",
    "Don't be afraid to take risks.",
    "The universe is full of wonders waiting to be explored.",
    "Your inner strength is greater than you realize.",
    "A good laugh heals a lot of hurt.",
    "The path to wisdom begins with curiosity.",
    "You will achieve your goals through perseverance.",
    "Cherish the present moment.",
    "Your positive attitude will take you far.",
    "The best things in life are free.",
    "You have the power to create your own happiness.",
    "Every challenge is an opportunity to grow.",
    "Your kindness will be returned to you.",
    "The key to success is to focus on goals, not obstacles.",
    "You are a unique and valuable individual.",
    "A new adventure awaits you.",
    "Your hard work will pay off.",
    "Listen to your heart.",
    "The best way to predict the future is to create it.",
    "You will find the answers you seek.",
    "Embrace change with open arms.",
    "Your potential is limitless.",
    "Small steps can lead to big changes.",
    "The greatest wealth is health.",
    "You will inspire others with your actions.",
    "Believe in your instincts.",
    "The world is full of beauty waiting to be seen.",
    "Your determination will lead to success.",
    "Find joy in the simple things.",
    "You have a gift to share with the world.",
    "The future is full of possibilities.",
    "Your courage will guide you.",
    "Take time to appreciate the good things in your life.",
    "You are stronger than you think.",
    "A positive outlook can change everything.",
    "The journey of self-discovery is a lifelong adventure.",
    "You will overcome any obstacles in your path.",
    "Let your light shine.",
    "The best is yet to unfold.",
    "Your wisdom will guide others.",
    "Embrace the present with gratitude.",
    "You have the power to make your dreams a reality.",
    "Every ending is a new beginning.",
    "Your enthusiasm is contagious.",
    "The path to happiness is paved with kindness.",
    "You will find peace within yourself.",
    "Believe in the magic of new beginnings.",
    "Your creativity knows no bounds.",
    "The greatest adventures are often the unexpected ones.",
    "You are loved and appreciated.",
    "Let your passions drive you.",
    "The world needs your unique talents.",
    "You will find clarity in unexpected moments.",
    "Embrace imperfections; they make you unique.",
    "Your resilience is admirable.",
    "The smallest gestures can have the biggest impact.",
    "You will be presented with an exciting opportunity.",
    "Trust the process of life.",
    "Your inner peace is your greatest strength.",
    "The universe supports your dreams.",
    "You will experience a moment of pure joy.",
    "Let kindness be your compass.",
    "Your perspective will bring new insights.",
    "Embrace the unknown with courage.",
    "You are on the right path.",
    "The seeds of happiness are within you.",
    "You will receive good news.",
    "Let your spirit soar.",
    "Your positive energy attracts positive outcomes.",
    "The best is always worth waiting for."
]

fortune = random.choice(fortunes)

context = {
    'fortune': fortune,
}

def fortune(request):
    return render(request, 'randomfortune/fortune.html', context)
